//
//  LegacyDataCleaner.swift
//  ShelfSense
//

import Foundation
import SwiftData

enum LegacyDataCleaner {
    private static let cleanedKey = "legacySampleDataRemoved_v2"

    /// Removes one-time demo seed data from earlier app versions.
    static func removeLegacySampleDataIfNeeded(context: ModelContext) {
        guard !UserDefaults.standard.bool(forKey: cleanedKey) else { return }

        let sampleStoreNames: Set<String> = [
            "Costco", "Target", "Trader Joe's", "Whole Foods", "CVS"
        ]
        let sampleProductNames: Set<String> = [
            "Whole Milk", "Organic Peanut Butter", "Paper Towels 12-pack",
            "Greek Yogurt 4-pack", "Laundry Pods"
        ]

        if let stores = try? context.fetch(FetchDescriptor<Store>()) {
            for store in stores where sampleStoreNames.contains(store.name) && store.address == "Near your current location (local only)" {
                context.delete(store)
            }
        }

        if let items = try? context.fetch(FetchDescriptor<InventoryItem>()) {
            for item in items where sampleStoreNames.contains(item.storeName ?? "") {
                context.delete(item)
            }
        }

        if let deals = try? context.fetch(FetchDescriptor<Deal>()) {
            for deal in deals where sampleProductNames.contains(deal.productName) {
                context.delete(deal)
            }
        }

        if let listItems = try? context.fetch(FetchDescriptor<ShoppingListItem>()) {
            for item in listItems where item.isAutoGenerated {
                context.delete(item)
            }
        }

        if let budgets = try? context.fetch(FetchDescriptor<Budget>()) {
            for budget in budgets where ["Groceries", "Household", "Costco"].contains(budget.name) {
                context.delete(budget)
            }
        }

        if let receipts = try? context.fetch(FetchDescriptor<Receipt>()) {
            for receipt in receipts where sampleStoreNames.contains(receipt.storeName) {
                context.delete(receipt)
            }
        }

        try? context.save()
        UserDefaults.standard.set(true, forKey: cleanedKey)
        UserDefaults.standard.removeObject(forKey: "hasSeededSampleData")
    }
}
