//
//  RestockService.swift
//  ShelfSense
//

import Foundation
import SwiftData

enum RestockService {
    static func syncShoppingList(context: ModelContext) {
        let itemDescriptor = FetchDescriptor<InventoryItem>()
        let listDescriptor = FetchDescriptor<ShoppingListItem>()

        guard let items = try? context.fetch(itemDescriptor),
              let existingList = try? context.fetch(listDescriptor) else { return }

        let autoGenerated = existingList.filter(\.isAutoGenerated)
        let lowStockItems = items.filter { $0.isLowStock }

        for item in lowStockItems {
            let alreadyListed = autoGenerated.contains {
                $0.name.localizedCaseInsensitiveCompare(item.name) == .orderedSame && !$0.isCompleted
            }
            guard !alreadyListed else { continue }

            let reason: String
            if let days = item.daysUntilRunOut {
                reason = "Running low — est. \(days) day\(days == 1 ? "" : "s") left"
            } else {
                reason = "Below minimum quantity"
            }

            context.insert(ShoppingListItem(
                name: item.name,
                brand: item.brand.isEmpty ? nil : item.brand,
                quantity: max(item.minimumQuantity - item.quantity, 1),
                quantityUnit: item.quantityUnit,
                isAutoGenerated: true,
                reason: reason,
                storeName: item.storeName,
                estimatedPrice: item.purchasePrice,
                priority: item.isExpiringSoon ? 3 : 2
            ))
        }

        try? context.save()
    }
}
