//
//  ShoppingListItem.swift
//  ShelfSense
//

import Foundation
import SwiftData

@Model
final class ShoppingListItem {
    var id: UUID
    var name: String
    var brand: String?
    var quantity: Double
    var quantityUnit: String
    var isCompleted: Bool
    var isAutoGenerated: Bool
    var reason: String?
    var storeName: String?
    var estimatedPrice: Double?
    var priority: Int
    var barcode: String?
    var caloriesPer100g: Double?
    var carbsPer100g: Double?
    var proteinPer100g: Double?
    var fatPer100g: Double?
    var fiberPer100g: Double?
    var sodiumPer100g: Double?
    var servingSize: String?
    var assignedTo: String?
    var createdAt: Date
    var household: Household?

    init(
        name: String,
        brand: String? = nil,
        quantity: Double = 1,
        quantityUnit: String = "units",
        isCompleted: Bool = false,
        isAutoGenerated: Bool = false,
        reason: String? = nil,
        storeName: String? = nil,
        estimatedPrice: Double? = nil,
        priority: Int = 0,
        barcode: String? = nil,
        caloriesPer100g: Double? = nil,
        carbsPer100g: Double? = nil,
        proteinPer100g: Double? = nil,
        fatPer100g: Double? = nil,
        fiberPer100g: Double? = nil,
        sodiumPer100g: Double? = nil,
        servingSize: String? = nil,
        assignedTo: String? = nil
    ) {
        self.id = UUID()
        self.name = name
        self.brand = brand
        self.quantity = quantity
        self.quantityUnit = quantityUnit
        self.isCompleted = isCompleted
        self.isAutoGenerated = isAutoGenerated
        self.reason = reason
        self.storeName = storeName
        self.estimatedPrice = estimatedPrice
        self.priority = priority
        self.barcode = barcode
        self.caloriesPer100g = caloriesPer100g
        self.carbsPer100g = carbsPer100g
        self.proteinPer100g = proteinPer100g
        self.fatPer100g = fatPer100g
        self.fiberPer100g = fiberPer100g
        self.sodiumPer100g = sodiumPer100g
        self.servingSize = servingSize
        self.assignedTo = assignedTo
        self.createdAt = Date()
    }
}
