//
//  ShoppingListView.swift
//  ShelfSense
//

import SwiftUI
import SwiftData

struct ShoppingListView: View {
    @Environment(\.modelContext) private var modelContext
    @Query(sort: \ShoppingListItem.priority, order: .reverse) private var items: [ShoppingListItem]
    @State private var showAddItem = false

    private var activeItems: [ShoppingListItem] {
        items.filter { !$0.isCompleted }
    }

    private var completedItems: [ShoppingListItem] {
        items.filter { $0.isCompleted }
    }

    private var estimatedTotal: Double {
        activeItems.compactMap(\.estimatedPrice).reduce(0, +)
    }

    var body: some View {
        NavigationStack {
            List {
                if !activeItems.isEmpty {
                    Section {
                        summaryBanner
                    }
                    .listRowInsets(EdgeInsets())
                    .listRowBackground(Color.clear)
                    .listRowSeparator(.hidden)
                }

                Section {
                    ForEach(activeItems, id: \.id) { item in
                        ShoppingListRow(item: item) {
                            toggleItem(item)
                        }
                    }
                    .onDelete(perform: deleteActiveItems)
                } header: {
                    if !activeItems.isEmpty {
                        Text("To Buy (\(activeItems.count))")
                    }
                }

                if !completedItems.isEmpty {
                    Section("Completed") {
                        ForEach(completedItems, id: \.id) { item in
                            ShoppingListRow(item: item, isCompleted: true) {
                                toggleItem(item)
                            }
                        }
                        .onDelete(perform: deleteCompletedItems)
                    }
                }

                if items.isEmpty {
                    Section {
                        emptyState
                    }
                    .listRowBackground(Color.clear)
                }
            }
            .listStyle(.insetGrouped)
            .scrollContentBackground(.hidden)
            .background(ShelfGradientBackground())
            .navigationTitle("Shopping List")
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button {
                        showAddItem = true
                        HapticManager.lightImpact()
                    } label: {
                        Image(systemName: "plus.circle.fill")
                            .foregroundStyle(ShelfTheme.accentSecondary)
                    }
                }
            }
            .sheet(isPresented: $showAddItem) {
                AddShoppingListItemView()
            }
        }
    }

    private var summaryBanner: some View {
        HStack(spacing: 16) {
            VStack(alignment: .leading, spacing: 4) {
                Text("Estimated Total")
                    .font(.shelfCaption)
                    .foregroundStyle(ShelfTheme.textSecondary)
                Text(Formatters.currencyString(estimatedTotal))
                    .font(.shelfStatSmall)
                    .foregroundStyle(ShelfTheme.textPrimary)
            }

            Spacer()

            VStack(alignment: .trailing, spacing: 4) {
                Text("Auto-generated")
                    .font(.shelfCaption)
                    .foregroundStyle(ShelfTheme.textSecondary)
                Text("\(activeItems.filter(\.isAutoGenerated).count) items")
                    .font(.shelfSubheadline)
                    .foregroundStyle(ShelfTheme.copperLight)
            }
        }
        .padding()
        .background(ShelfTheme.cardBackground)
        .clipShape(RoundedRectangle(cornerRadius: ShelfTheme.cornerRadiusMedium, style: .continuous))
        .padding(.vertical, 4)
    }

    private var emptyState: some View {
        VStack(spacing: 12) {
            Image(systemName: "checklist")
                .font(.largeTitle)
                .foregroundStyle(ShelfTheme.textTertiary)
            Text("Your list is empty")
                .font(.shelfHeadline)
                .foregroundStyle(ShelfTheme.textSecondary)
            Text("Tap + to add items with brand and nutrition info")
                .font(.shelfCaption)
                .foregroundStyle(ShelfTheme.textTertiary)
                .multilineTextAlignment(.center)
            Button("Add Item") {
                showAddItem = true
            }
            .font(.shelfSubheadline)
            .foregroundStyle(ShelfTheme.copperLight)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 32)
    }

    private func toggleItem(_ item: ShoppingListItem) {
        withAnimation(.spring(response: 0.3)) {
            item.isCompleted.toggle()
        }
        HapticManager.selection()
    }

    private func deleteActiveItems(at offsets: IndexSet) {
        for index in offsets {
            modelContext.delete(activeItems[index])
        }
    }

    private func deleteCompletedItems(at offsets: IndexSet) {
        for index in offsets {
            modelContext.delete(completedItems[index])
        }
    }
}

struct ShoppingListRow: View {
    let item: ShoppingListItem
    var isCompleted: Bool = false
    let onToggle: () -> Void

    var body: some View {
        Button(action: onToggle) {
            HStack(spacing: 12) {
                Image(systemName: isCompleted ? "checkmark.circle.fill" : "circle")
                    .foregroundStyle(isCompleted ? ShelfTheme.success : ShelfTheme.textTertiary)
                    .font(.title3)

                VStack(alignment: .leading, spacing: 4) {
                    Text(item.name)
                        .font(.shelfSubheadline)
                        .foregroundStyle(isCompleted ? ShelfTheme.textTertiary : ShelfTheme.textPrimary)
                        .strikethrough(isCompleted)

                    HStack(spacing: 6) {
                        if let brand = item.brand, !brand.isEmpty {
                            Text(brand)
                                .font(.shelfCaption)
                                .foregroundStyle(ShelfTheme.copperLight)
                        }

                        if let reason = item.reason {
                            Text(reason)
                                .font(.shelfCaption)
                                .foregroundStyle(ShelfTheme.accent)
                        } else if item.isAutoGenerated {
                            Label("AI suggested", systemImage: "sparkles")
                                .font(.shelfCaption)
                                .foregroundStyle(ShelfTheme.textTertiary)
                        }
                    }

                    if let nutrition = nutritionLine {
                        Text(nutrition)
                            .font(.system(size: 10, weight: .medium))
                            .foregroundStyle(ShelfTheme.textSecondary)
                    }
                }

                Spacer()

                VStack(alignment: .trailing, spacing: 2) {
                    Text("\(item.quantity.formatted(.number.precision(.fractionLength(0...1))))")
                        .font(.shelfCaption)
                        .foregroundStyle(ShelfTheme.textSecondary)

                    if let price = item.estimatedPrice {
                        Text(Formatters.currencyString(price))
                            .font(.shelfCaption)
                            .foregroundStyle(ShelfTheme.textTertiary)
                    }
                }
            }
        }
        .buttonStyle(.plain)
    }

    private var nutritionLine: String? {
        var parts: [String] = []
        if let cal = item.caloriesPer100g { parts.append("\(Int(cal)) cal/100g") }
        if let carbs = item.carbsPer100g { parts.append("\(Formatters.decimalString(carbs))g carbs") }
        if let protein = item.proteinPer100g { parts.append("\(Formatters.decimalString(protein))g protein") }
        return parts.isEmpty ? nil : parts.joined(separator: " · ")
    }
}

#Preview {
    ShoppingListView()
        .modelContainer(PreviewModelContainer.shared)
}
